### PR TITLE
BUG required text matches NXDL name

### PR DESCRIPTION
**Pull request by prjemian**
We need to ensure the required text of an NXDL `definition` matches its name.

Not sure that order of the XML elements matter.  Usually, I put the `definition` element first so that I don't forget to synchronize this important detail.

### CODE REVIEW

**Comment by prjemian** [comment]
Also, the indentation could be cleaned up.  If the documentation builds, then it must be good enough.  Can you build the documentation for your branch and check it?

**Comment by prjemian** [comment]
@aaron-parsons I have a change in the works for you.  Seems I have made a PR to my fork of your fork.  Take a look at it please.

**Comment by aaron-parsons** [comment]
HI @prjemian Sorry for taking so long to get back to this.

I agree with this change. I'll make it on my fork now.

**Comment by prjemian** [comment]
That is, you merge the PR

**Comment by aaron-parsons** [comment]
HI @prjemian , 

The PR here is into the master branch of your fork, so I don't have permissions to merge it I'm afraid. I instead just made the change on https://github.com/aaron-parsons/definitions/tree/patch-1 which is the PR into the definitions repo.

I hope that's ok.

Aaron

**Comment by prjemian** [comment]
That's fine.  Thanks!

**Pull request closed without merging**
